#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Dashboard.Views.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NuGetGallery.Dashboard.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public static class Nav
    {
        
        #line 2 "..\..\Views\Helpers\Nav.cshtml"

    private static object _currentAreaKey = new object();
    
    public new static WebViewPage CurrentPage {
        get { return (WebViewPage)HelperPage.CurrentPage; }
    }

        #line default
        #line hidden

public static System.Web.WebPages.HelperResult AreaMenu(string areaName, string areaTitle, string areaIcon, Func<object, HelperResult> menuContent) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 10 "..\..\Views\Helpers\Nav.cshtml"
                                                                                                              
    var activeClass = String.Equals((string)CurrentPage.ViewContext.RouteData.DataTokens["area"], areaName, StringComparison.OrdinalIgnoreCase) ? "active" : null;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li class=\"dropdown ");



#line 12 "..\..\Views\Helpers\Nav.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, activeClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"" +
"");



#line 13 "..\..\Views\Helpers\Nav.cshtml"
                                  WebViewPage.WriteTo(@__razor_helper_writer, areaIcon);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i> ");



#line 13 "..\..\Views\Helpers\Nav.cshtml"
                                                  WebViewPage.WriteTo(@__razor_helper_writer, areaTitle);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <b class=\"caret\"></b></a>\r\n        <ul class=\"dropdown-menu\">\r\n");



#line 15 "..\..\Views\Helpers\Nav.cshtml"
               
                var oldArea = CurrentPage.Context.Items[_currentAreaKey];
                CurrentPage.Context.Items[_currentAreaKey] = areaName; 
                
#line default
#line hidden


#line 18 "..\..\Views\Helpers\Nav.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, menuContent(null));

#line default
#line hidden


#line 18 "..\..\Views\Helpers\Nav.cshtml"
                                  
                CurrentPage.Context.Items[_currentAreaKey] = oldArea;
            

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </li>\r\n");



#line 23 "..\..\Views\Helpers\Nav.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult MenuAction(string actionName, string controllerName, string icon, string title) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 25 "..\..\Views\Helpers\Nav.cshtml"
                                                                                         
    var areaName = (string)CurrentPage.Context.Items[_currentAreaKey];
    var active =
        (String.Equals(actionName, (string)CurrentPage.ViewContext.RouteData.Values["action"], StringComparison.OrdinalIgnoreCase) &&
         String.Equals(controllerName, (string)CurrentPage.ViewContext.RouteData.Values["controller"], StringComparison.OrdinalIgnoreCase) &&
         String.Equals(areaName, (string)CurrentPage.ViewContext.RouteData.DataTokens["area"], StringComparison.OrdinalIgnoreCase)) 
         ? "active" 
         : null;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li class=\"");



#line 33 "..\..\Views\Helpers\Nav.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, active);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"><a href=\"");



#line 33 "..\..\Views\Helpers\Nav.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, CurrentPage.Url.Action(actionName, controllerName, new { area = areaName }));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"><i class=\"");



#line 33 "..\..\Views\Helpers\Nav.cshtml"
                                                                              WebViewPage.WriteTo(@__razor_helper_writer, icon);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i> ");



#line 33 "..\..\Views\Helpers\Nav.cshtml"
                                                                                          WebViewPage.WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 34 "..\..\Views\Helpers\Nav.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
